version: '3.8'
services:
  db:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=my-dinner
      - MYSQL_PASSWORD=my-dinner
      - MYSQL_DATABASE=my-dinner
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - backendnetwork
  backend:
    build:
      context: .
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://db/my-dinner
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    depends_on:
      - db
    networks:
      - backendnetwork
      - proxy
volumes:
  mysql_data:
  mysql_config:

networks:
  backendnetwork:
  proxy:
    external: true
